version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: verifynews_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: verifynews_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses="*"

  # pgadmin:
  #     image: dpage/pgadmin4
  #     container_name: pgadmin
  #     depends_on:
  #       - postgres
  #     ports:
  #       - "5051:80"
  #     environment:
  #       PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #       PGADMIN_DEFAULT_PASSWORD: root
  #     restart: always



  docs:
    image: verifynews_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./verifynews:/app/verifynews:z
    ports:
      - "7000:7000"
    command: /start-docs
